### ISSUE TITLE
Accounts with duplicate names are missing in balance export

### ISSUE THREAD

**Issue by some-guy-23** [monarchmoney/mint-export-extension#20]
I have quite a few old / closed accounts with names that are identical to the new updated accounts. This could also be the case with generic account names like "Credit Card". Looks like in this case it will only export the last account w/ that name.

Can the csv filename be updated to a format of "Account Name - (Account ID).csv" or such, so they won't be lost during export?

**Comment by vanessa** [comment]
Fixed by #19.
