### ISSUE TITLE
Add Institution to the account

### ISSUE THREAD

**Issue by jhicken** [monarchmoney/mint-export-extension#36]
Account has an attribute of "fiName". It would be neato if that was included on the exported data. In my particular case I have 2 accounts that are named exactly the same thing. So this would help to distinguish which account this account really is.

https://github.com/monarchmoney/mint-export-extension/blob/1aa8ffc64a584950cba70e68008bed90d74ba8e3/src/shared/lib/accounts.ts#L259 (Right around here is where the change would need to be made)

Another small observation. Maybe Monarch is using this data but the "Account Name" column in the mint-balances csv files, could probably go away. It's repetitive data that just makes the csv files larger. And the file name of the csv is the account name already. 

Thanks for building this. I have around 15 years of data in mint that would be really sad to lose. So I appreciate you guys!

**Comment by MilesBHuff** [comment]
I believe this issue can be closed, given that the PR for it has been merged.
